services:
    bookToRedisForAdd:
        class: Wcms\PhonebookBundle\EventListener\BookToRedis
        arguments:
            - '@snc_redis.default'
        tags:
            -
                name: doctrine.event_listener
                event: postPersist
            -
                name: doctrine.event_listener
                event: preUpdate
            -
                name: doctrine.event_listener
                event: postUpdate
            -
                name: doctrine.event_listener
                event: postRemove